name: flutter_module
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  #hybrid_stack_manager: 0.0.6
  flutter:
    sdk: flutter
  battery_level:
    path: ../flutter_plugins/battery_level

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.fluttermodule
    iosBundleIdentifier: com.example.flutterModule
